common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
development:
  <<: *common
  database: ticketee_development
  username: develop
  password: developR1 
test: &test
  <<: *common
  database: ticketee_test
  username: develop
  password: developR1
production:
  <<: *common
  database: ticketee_production
  username: ticketee
  password: foobar
cucumber:
  <<: *test