common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: develop
  password: developR1


development:
  <<: *common
  database: ticketee_development
test: &test
  <<: *common
  database: ticketee_test
production:
  <<: *common
  database: ticketee_production
cucumber:
  <<: *test